version: 2.1
# Use a package of configuration  called an orb.

  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
orbs:
   aws-cli: circleci/aws-cli@2.0.3
jobs:
  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["7b:24:6a:c4:2e:2e:d4:4b:52:49:0b:19:de:90:af:59"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            pip install --user ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml
  # Exercise: Smoke Testing
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi

The new job should:
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - smoke_test